name: IZUAL_Documents_Github_Pages

on:
  push:
    branches:
      - master # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
<<<<<<< HEAD
          github_token: ${{ secrets.IZUAL_Documents_Github_Pages }}
=======
          github_token: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 64123bca621cccbd21a865486b521f6194bc0871
          publish_dir: ./docs-dist